### ISSUE TITLE
 Is poppler installed and in PATH ? 

### ISSUE THREAD

**Issue by ghost** [LJSthu/Python-Remove-Watermark#5]
求助，报错： Is poppler installed and in PATH ? 
在网上搜索了一番没有找到解决办法，已经按照readme安装了需要的pip包。
```
Traceback (most recent call last):
  File "/Users/kasusa/Documents/GitHub/Python-Remove-Watermark/watermark.py", line 58, in <module>
    images = convert_from_path('/Users/kasusa/Documents/GitHub/Python-Remove-Watermark/a.pdf')
  File "/Users/kasusa/Library/Python/3.9/lib/python/site-packages/pdf2image/pdf2image.py", line 98, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "/Users/kasusa/Library/Python/3.9/lib/python/site-packages/pdf2image/pdf2image.py", line 484, in pdfinfo_from_path
    raise PDFInfoNotInstalledError(
pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
```

**Comment by abdulmukit-n** [comment]
Any resolution to this problem @kasusa ?

**Comment by turingzz** [comment]
Unable to get page count. Is poppler installed and in PATH?

**Comment by ben0i0d** [comment]
I don't see such a problem, if there is a scene, maybe I can help

**Comment by lix19937** [comment]
install poppler https://github.com/oschwartz10612/poppler-windows/tags , and then 
```py
images = convert_from_path('cuda-graph-introduction.pdf',
                           poppler_path=r'E:\python_workspace_transformer\Python-Remove-Watermark-master\poppler-24.07.0\Library\bin')
# images = np.array(images)
index = 0
```

**Comment by ben0i0d** [comment]
hello , i've done this.
I rewrite with pymupdf to remove poppler.
Please look my repo.(of course , the PR #7 )
